dataset_name: ADE20K
model_name: deeplabv3

image_dir: '/fast/AG_Kainmueller/data/ADEChallengeData2016/images/validation'
label_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/annotations/validation
prediction_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/predictions/deeplabv3_r50-d8_4xb4-160k_ade20k-512x512/predictions/
uq_map_dir: /fast/AG_Kainmueller/data/UQ_maps/ADE20K/validation_deeplabv3/semantic/dropout/pu/
metadata_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/objectInfo150.json