name: aggr_experiments
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - h5py
  - imagecodecs
  - ipython
  - jupyterlab
  - matplotlib
  - numba
  - numcodecs
  - pandas
  - pillow
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - pytorch
  - torchvision
  - tqdm
  - pip:
      - -e .