dataset_name: ADE20K
model_name: deeplab

image_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/images/validation
label_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/annotations/validation
prediction_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/deeplabv3_r50-d8_4xb4-160k_ade20k-512x512/UQ_predictions
uq_map_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/deeplabv3_r50-d8_4xb4-160k_ade20k-512x512/UQ_maps
metadata_dir: /fast/AG_Kainmueller/data/ADEChallengeData2016/deeplabv3_r50-d8_4xb4-160k_ade20k-512x512/UQ_metadata

num_classes: 150

uq_method: dropout
num_dropout_samples: 15

normalized_maps: True
map_dimension: 3
