[paths]
id_csv_path_spatial = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/spatial_fingerprint_arctique_semantic_blood_cells_0_00_tta_pu.csv'
ood_csv_path_spatial = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/spatial_fingerprint_arctique_semantic_blood_cells_0_75_tta_pu.csv'
id_csv_path_magnitude = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/aggregation_value_summary_joint_noise_arctique_semantic_blood_cells_tta_pu_0_00.csv'
ood_csv_path_magnitude = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/aggregation_value_summary_joint_noise_arctique_semantic_blood_cells_tta_pu_0_75.csv'

[splits]
id_json_path_spatial = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/spatial/splits/semantic_arctique_blood_cells_pu_test_split.json'
ood_json_path_spatial = ''

[dataset]
task = 'semantic' #or 'instance'
dataset_name = 'arctique'
variation = 'blood_cells' #or 'nuclei_intensity'
noise_level = '0_75'

[pm]
uq_method = 'tta'