[paths]
id_csv_path_spatial = LAB_PATH + 'vguarin/aggrigator_experiments/output/tables/spatial_fingerprint_lizard_semantic_glas_set_0_00_dropout_pu.csv'
ood_csv_path_spatial = LAB_PATH + 'vguarin/aggrigator_experiments/output/tables/spatial_fingerprint_lizard_semantic_glas_set_1_00_dropout_pu.csv'
id_csv_path_magnitude = LAB_PATH + 'vguarin/aggrigator_experiments/output/tables/aggregation_value_summary_joint_noise_lizard_semantic_glas_set_dropout_pu_0_00.csv'
ood_csv_path_magnitude = LAB_PATH + 'vguarin/aggrigator_experiments/output/tables/aggregation_value_summary_joint_noise_lizard_semantic_glas_set_dropout_pu_1_00.csv'

[splits]
id_json_path_spatial = LAB_PATH + 'vguarin/aggrigator_experiments/spatial/splits/semantic_lizard_glas_set_pu_test_split.json' #already has the correct padded tiles inside
ood_json_path_spatial = ''

[dataset]
task = 'semantic' #or 'instance'
dataset_name = 'lizard'
variation = 'glas_set' 

[pm]
uq_method = 'dropout'