[paths]
id_csv_path_spatial = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/spatial_fingerprint_wormbodies_0_00_dropout_pu.csv'
ood_csv_path_spatial = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/spatial_fingerprint_wormbodies_nematodes_1_00_dropout_pu.csv'
id_csv_path_magnitude = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/aggregation_value_summary_joint_noise_wormbodies_fgbg_nematodes_dropout_pu_0_00.csv'
ood_csv_path_magnitude = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/output/tables/aggregation_value_summary_joint_noise_wormbodies_fgbg_nematodes_dropout_pu_1_00.csv'

[splits]
id_json_path_spatial = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/spatial/splits/fgbg_wormbodies_nematodes_pu_test_split.json'
ood_json_path_spatial = '/fast/AG_Kainmueller/vguarin/aggrigator_experiments/spatial/splits/fgbg_wormbodies_nematodes_pu_ood_split.json'

[dataset]
task = 'fgbg' #protists
dataset_name = 'wormbodies'
variation = 'nematodes' #protists

[pm]
uq_method = 'dropout'